### ISSUE TITLE
typo in htmldumper.js

### ISSUE THREAD

**Issue by nitingupta910** [wikimedia/htmldumper#1]
Fix: not a nodejs expert but looks like this is the fix:

diff --git a/htmldumper.js b/htmldumper.js
index cdd213a..f7807ab 100644
--- a/htmldumper.js
+++ b/htmldumper.js
@@ -1,6 +1,6 @@
 "use strict";

-if (!global.Promise || !global.promise.promisify) {
+if (!global.Promise || !global.Promise.promisify) {
     global.Promise = require('bluebird');
 }

**Comment by gwicke** [comment]
Heh, good catch! That would make a difference on node 0.12 & iojs.

**Comment by gwicke** [comment]
Fixed by 4e5fd1449815a6e54. Closing.
