### ISSUE TITLE
Error in makeDump

### ISSUE THREAD

**Issue by nitingupta910** [wikimedia/htmldumper#2]
No article could be fetched. All fail with the same error (log provided below)

_NOTE_: I'm behind a proxy but not sure if this error is because of that (both `http_proxy` and `https_proxy` are set correctly)
## Platform

`node --version`
v0.10.36
Fedora 21 x86_64
## Command

`
htmldumper.js --prefix en.wikipedia.org   --ns 0 --apiURL http://en.wikipedia.org/w/api.php   --host https://rest.wikimedia.org/ --saveDir ~/temp/wp
`
## Error Log

```
Error in makeDump: 'N_Everything 584723596 { [HTTPError: 404: https://restbase.org/errors/not_found#proxy_handler]
  name: 'HTTPError',
  message: '404: https://restbase.org/errors/not_found#proxy_handler',
  status: 404,
  headers: 
   { server: 'nginx/1.1.19',
     date: 'Thu, 12 Mar 2015 23:14:04 GMT',
     'content-type': 'application/problem+json',
     'content-length': '98',
     connection: 'keep-alive',
     'access-control-allow-origin': '*',
     'access-control-allow-methods': 'GET',
     'access-control-allow-headers': 'accept, content-type',
     'accept-ranges': 'bytes',
     'x-varnish': '2050373846',
     age: '0',
     via: '1.1 varnish',
     'x-cache': 'cp1045 frontend miss (0)' },
  body: 
   { type: 'https://restbase.org/errors/not_found#proxy_handler',
     title: 'Not found.',
     method: 'get' } }
```

**Comment by gwicke** [comment]
It works for me without the slash at the end of the host parameter, as recommended by --help:

```
--host https://rest.wikimedia.org
```

**Comment by gwicke** [comment]
@nitingupta910, I also just pushed a changeset that strips trailing slashes, so even your older invocation should work now.
